title: <font color = "black">Ajay Ramesh Ranganathan </font>
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  International Institute of Information Technology Bangalore (IIIT-B)
  <br><br>
  Integrated Masters in Electronics and Communication Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/ajay-ramesh-06a188190/">Visit My LinkedIn Profile</a>
  <br><br>
theme: jekyll-theme-minimal
